### ISSUE TITLE
Mnogo webemok

### ISSUE THREAD

**Issue by pwf63158cdnqacom** [CherryPerry/ffmpeg-vp9-wrap#1]
При прописывании, например, 
vp9 -file or.mkv -subs or.ass -ss 05:43.335 -to 06:32.731 -limit 10240 -alimit
Создается две вебмки, одна меньшего размера, чем вторая. И еще вторая получилась в 10.11 мб и превысила лимит.

**Comment by CherryPerry** [comment]
**Не баг, а фича.**

Здесь стоит рассказать о том, как вообще подгоняется под лимит.
Используется та самая формула с пикчегайда bitrate = (limit - audio) / length. Однако последние версии libvpx сжимают до еще меньшего битрейта (бывает и большего).

![default](https://cloud.githubusercontent.com/assets/9081555/8747426/a5b76624-2c9b-11e5-891b-a04349649ddc.png)

Поскольку эту кривую невозможно (или возможно но я не знаю как) вывести теоретически, остается только выгадывать нужный теоретический битрейт, чтобы практический был под лимит. Сначала высчитывается битрейт под лимит 10240, потом, к примеру, под 15400 (определяется через аппроксимацию в прямые, т.е. построение графика).

Webm'ки сохраняются на каждом шаге для безопасности:
- программа может упасть
- программа может зациклиться (хотя подгон останавливается если на двух шагах получена webm с одним и тем же размером)

И да, поскольку имеет место метод околонаучного тыка, то на одном из шагов могут получаться webm большего размера.
Алсо -limit 10240 можно не указывать, по дефолту 10240, пиши сразу
`
vp9 -file or.mkv -subs or.ass -ss 05:43.335 -to 06:32.731 -alimit
`

**Comment by pwf63158cdnqacom** [comment]
Так и думал, что так и надо. Не очень хочется ждать обработки видео два раза вместо одного, ну да и ладно.
